---
env:
  global:
    - CC_TEST_REPORTER_ID=478e3a94a1ec879002f32677426e1cb4409caa8a232028b2efd662fd0ce2b346
language: node_js

node_js:
- node
- lts/*

sudo: false

cache:
  directories:
  - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- npm run test:coverage
- npm run lint

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT